spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=devquery;encrypt=true;trustServerCertificate=true;loginTimeout=10;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23ctgEc8iZfNRFcmVz
spring.security.oauth2.client.registration.github.client-secret=1c0dd8b9afaae8bc17944dfd95a581fc15869daf

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=506908692355-hjo25b3i4fn65okidkdsc3qr3sn60pcl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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