spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=devquery;encrypt=true;trustServerCertificate=true;loginTimeout=10;
spring.datasource.username=SA
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23ctgEc8iZfNRFcmVz
spring.security.oauth2.client.registration.github.client-secret=${DEVQUERY_GITHUB_CLIENT_SECRET}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=506908692355-9sroijeqpmfornscd14lbf8nh9ml3tcu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${DEVQUERY_GOOGLE_CLIENT_SECRET}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${DEVQUERY_MAIL_USERNAME:}
spring.mail.password=${DEVQUERY_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=${DEVQUERY_APP_BASE_URL:http://localhost:8080}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.security.oauth2.client.registration.google.scope=profile,email

# Spring AI - Google GenAI Configuration
spring.ai.google.genai.api-key=${DEVQUERY_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite