server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/devquery?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23ctgEc8iZfNRFcmVz
spring.security.oauth2.client.registration.github.client-secret=1c0dd8b9afaae8bc17944dfd95a581fc15869daf

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=506908692355-hjo25b3i4fn65okidkdsc3qr3sn60pcl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${DEVQUERY_MAIL_USERNAME:}
spring.mail.password=${DEVQUERY_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=${DEVQUERY_APP_BASE_URL:http://localhost:8080}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.security.oauth2.client.registration.google.scope=profile,email

devquery.ai.api-key= AIzaSyCo8VbYqpG1qgSS8pNJrnPxi3Y9r7Ee-xg
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite
